package org.tmf.dsmapi.subAddress;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.tmf.dsmapi.commons.facade.AbstractFacade;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.tmf.dsmapi.commons.exceptions.BadUsageException;
import org.tmf.dsmapi.commons.exceptions.ExceptionType;
import org.tmf.dsmapi.commons.exceptions.UnknownResourceException;
import org.tmf.dsmapi.commons.utils.BeanUtils;
import org.tmf.dsmapi.address.model.SubAddress;
import org.tmf.dsmapi.subAddress.event.SubAddressEventPublisherLocal;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;

@Stateless
public class SubAddressFacade extends AbstractFacade<SubAddress> {

    @PersistenceContext(unitName = "DSAddressPU")
    private EntityManager em;
    @EJB
    SubAddressEventPublisherLocal publisher;
//    StateModelImpl stateModel = new StateModelImpl();

    public SubAddressFacade() {
        super(SubAddress.class);
    }

    @Override
    protected EntityManager getEntityManager() {
        return em;
    }

    public void checkCreation(SubAddress entity) throws BadUsageException, UnknownResourceException {

        SubAddress sc = null;
        if (entity.getId() == null
                || entity.getId().isEmpty()) {
//            throw new BadUsageException(ExceptionType.BAD_USAGE_GENERIC, "While creating SubAddress, id must be not null");
                //Do nothing create ok
                Logger.getLogger(SubAddressFacade.class.getName()).log(Level.INFO, "SubAddress with autogenerated id is being posted");
        } else {
            try {
                sc = this.find(entity.getId());
                if (null != sc) {
                    throw new BadUsageException(ExceptionType.BAD_USAGE_GENERIC,
                            "Duplicate Exception, SubAddress with same id :" + entity.getId() + " alreay exists");
                }
            } catch (UnknownResourceException ex) {
                //Do nothing create ok
                Logger.getLogger(SubAddressFacade.class.getName()).log(Level.INFO, "SubAddress with id = " + entity.getId() + " is being posted", ex);
            }
        }

        //verify first status
        /**
        if (null == entity.getLifecycleState()) {
            entity.setLifecycleState(LifecycleStateValues.PENDING);
            throw new BadUsageException(ExceptionType.BAD_USAGE_MANDATORY_FIELDS, "LifecycleState is mandatory");
        } else {
            if (!entity.getLifecycleState().name().equalsIgnoreCase(LifecycleStateValues.PENDING.name())) {
                throw new BadUsageException(ExceptionType.BAD_USAGE_FLOW_TRANSITION, "lifecycleState " + entity.getLifecycleState().value() + " is not the first state, attempt : " + LifecycleStateValues.PENDING.value());
            }
        }
        */

    }

    public SubAddress patchAttributs(String id, SubAddress partialEntity) throws UnknownResourceException, BadUsageException {
        SubAddress currentEntity = this.find(id);

        if (currentEntity == null) {
            throw new UnknownResourceException(ExceptionType.UNKNOWN_RESOURCE);
        }

        verifyStatus(currentEntity, partialEntity);

        ObjectMapper mapper = new ObjectMapper();
        JsonNode node = mapper.convertValue(partialEntity, JsonNode.class);
        partialEntity.setId(id);
        if (BeanUtils.patch(currentEntity, partialEntity, node)) {
            publisher.valueChangedNotification(currentEntity, new Date());
        }

        return currentEntity;
    }

    public void verifyStatus(SubAddress currentEntity, SubAddress partialEntity) throws BadUsageException {
        /**
        if (null != partialEntity.getLifecycleState()) {
            stateModel.checkTransition(currentEntity.getLifecycleState(), partialEntity.getLifecycleState());
            publisher.statusChangedNotification(currentEntity, new Date());
        }
        */
    }

}
